[phases.setup]
nixPkgs = ['nodejs_20', 'npm-10_x', 'openssl']

[phases.install]
cmds = [
  'rm -rf node_modules package-lock.json',
  'npm install --legacy-peer-deps'
]

[phases.build]
cmds = [
  'rm -rf .next/cache',
  'npx prisma generate',
  'npm run build'
]

[start]
cmd = 'bash start.sh'

[variables]
NODE_ENV = 'production'
